//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Convertec_Bodega_Administracion.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConvertecBodegaEntities : DbContext
    {
        public ConvertecBodegaEntities()
            : base("name=ConvertecBodegaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Imagen_Producto> Imagen_Producto { get; set; }
        public virtual DbSet<Ingreso_Prod> Ingreso_Prod { get; set; }
        public virtual DbSet<Marca> Marca { get; set; }
        public virtual DbSet<Movimiento> Movimiento { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<Salida_Prod> Salida_Prod { get; set; }
        public virtual DbSet<Trabajador> Trabajador { get; set; }
    }
}
