//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Convertec_Bodega_Administracion.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingreso_Prod
    {
        public long id_mov { get; set; }
        public int id_proveedor { get; set; }
        public int id_marca { get; set; }
        public string cod_prod_prov { get; set; }
        public string documento { get; set; }
        public int valor { get; set; }
        public Nullable<int> valor_unitario { get; set; }
    
        public virtual Marca Marca { get; set; }
        public virtual Movimiento Movimiento { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
