//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Convertec_Bodega_Administracion.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salida_Prod
    {
        public long id_mov { get; set; }
        public int id_trabajador { get; set; }
        public int folio { get; set; }
    
        public virtual Movimiento Movimiento { get; set; }
        public virtual Trabajador Trabajador { get; set; }
    }
}
